config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'

  root 'pages#one'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-inverse bg-warning">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Link a Página1', pages_one_path %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Link a Página2', pages_two_path %>
          </li>
          <li class="nav-item">
            <%= link_to 'Link a Página3', pages_three_path %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Yannick Michel Brionne Delgado</h1>

<div class="jumbotron">
  <h1 class="display-4">BIENVENIDOS A MI PÁGINA XD</h1>
  <a class="btn btn-primary btn-lg" href="#" role="button">A dónde?</a>
</div

app/views/pages/three.html.erb
<h2>Página Tres</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid temporibus, quis iure iusto, repellendus laboriosam, maiores porro qui, vitae tenetur quod eligendi at tempore nihil rem. Consequatur dolores, eum inventore!</p>

app/views/pages/two.html.erb
<h1>EL GRAN PANTALLAZO</h1>

<%= image_tag 'pantalla.png' %>